name: Clement
favicon: null
layout_spectrum: 0.24047
typography_spectrum: 0.56891
title: Clement
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#262626'
    - '#727272'
    - '#b4b4b4'
  brandStrength: 0.3125
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
