name: Clement
favicon: null
layout_spectrum: 0.06088
typography_spectrum: 0.82227
title: Clement
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161d23'
    - '#e0dede'
    - '#6c7789'
    - '#aba864'
    - '#42a644'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
