name: Clement
favicon: null
layout_spectrum: 0.3254583009984344
typography_spectrum: 0.90285
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161d23'
    - '#cccccc'
    - '#ffffff'
    - '#828282'
    - '#42a644'
  brandStrength: 0.125
  lightness: 0.8522257956210524
  saturation: 0.5
  rhythmicContrast: 0.687920723343268
purpose: []
