name: Clement
favicon: null
layout_spectrum: 0.3254583009984344
typography_spectrum: 0.10670230770483613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7003816778305918
  lightness: 0.8522257956210524
  saturation: 0.6945343918632716
  rhythmicContrast: 0.687920723343268
purpose: []
